/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fe826577-682a-402b-95c6-8275149d6fb9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4WMx0YrKR",
    "aws_user_pools_web_client_id": "6rnhvhqj16kt6gqii0lbumkg24",
    "oauth": {}
};


export default awsmobile;
